# 2. Wow, this will be easy....
# Look at this series: 2, 2, 4, 12, 48, … the seed for this series was the number 2.
# Look at this series: 3, 3, 6, 18, 72, … the seed for this series was the number 3.
# Create a function that receives two integers: x, and y. If any of them are 0 or negative, or if
# they are greater than 255, the function should return -1
# The function should return the y element of the series generated by x.
# For example, if the series receives x = 3, y = 4, it should return 72, because 72 is the 4th
# element of the series generated when x = 3.
# The function will receive 2 integers, and return an integer
# David Avarez C

def exercise_2(x, y):
    
    
    if x <0  or y < 0 or y>255 or x> 255:
        print('Los parametros deben estar dentro del domino establecido')
        return -1
    else:
        out = 0 
        serie =[x]
        if x == 3:
            for i in range(1,y+1):
                serie.append(serie[-1] * i)
            out = serie[-1]
            return out
        if x == 2:
            for i in range(1, y+1):
                serie.append(serie[-1] * i)
            out = serie[-1]
            return out
            
if __name__ == '__main__':
    print(exercise_2(2,3))
    print(exercise_2(3, 9))
    print(exercise_2(3, 4))


    
