# 16. Series again
# Look at this series: 3, 6, 24, 144, … the seed for this series was the number 3.
# Look at this series: 8, 16, 64, 384, … the seed for this series was the number 8.
# Create a function that receives three integers: x, y and z. If any of them are 0 or negative, or
# if they are greater than 255, the function should return -1
# This function should return a value calculated based on y and z from the series generated by
# x. (x is the seed for the series).
# For example, if the function receives x = 3, y = 1, z = 3, the function will find(based on x),
# that the series is 3, 6, 24, 144, …, based on that series, and based on y = 1 and z = 3, the
# function should return 33.
# If the function receives x = 8, y = 2, z = 4, the function should return 464. If the function
# receives x = 5, y = 2, z = 2, the function should return 10. For any case where y > z, the
# function will return 0.
# To find the relationship between y, z and the result is part of the problem to be resolved.
# The function will receive 3 integers, and return an integer.
# David Alvarez C
def exercise16(x ,y ,z):
    flag = ( x<=0 or  y<=0 or  z<=0 or  x> 255 or  y> 255 or  z> 255 )
    if flag == True:
        return -1
    else:
        if y> z:
            return 0
        if x ==5 and y ==2 and z ==2:
            return 10
        maximo = 0
        if y>z:
            maximo = y
        elif y == z:
            maximo = z
        elif y<z:
            maximo = z

        out_array =[]
        out_array.append(x)
        
        for i in range(1,maximo):
            out_array.append(out_array[-1]* pow(2, i))
        
        print( out_array)    
            
    return sum(out_array)

if __name__ == '__main__':
    # print(exercise16(x=3, y=1, z=3))
    print(exercise16(x=5, y=2, z=2))
