# 3. That was pretty easy, give me another...
# Look at this series: 60, 30, 20, 15, 12... the seed for this series was the number 60.
# Create a function that receives two integers: x, and y. If any of them are 0 or negative, or if
# they are greater than 255, the function should return -1.
# The function should return the y element of the series generated by x.
# For example: If the function receives x = 60, y = 3, it will return 20, because 20 is the 3th
# element in the series generated when x = 60.
# The function will receive 2 integers, return a floating point value.
# David Avarez C

# factors primes
def exercise_3(x, y):
    
    if x < 0 or x > 255 or y < 0 or y > 255:
        print('Los parametros deben estar dentro del domino establecido')
        return -1
    else:
        out = [ _ for _ in range(1,x+1) if x % _ ==0 ]
        out = list(reversed(out))

        print(out)
        return out[y-1]
            
if __name__ == '__main__':
    print(exercise_3(60, 3))
    print(exercise_3(60, 4))
    print(exercise_3(60, 5))


    
